# Generated by Django 4.2 on 2024-07-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultchecked',
            old_name='radio_name',
            new_name='radio_value',
        ),
    ]
